name: Hlidac bytu

on:
  schedule:
    - cron: "*/30 * * * *"   # každých 30 minut
  workflow_dispatch:

jobs:
  run-hlidac:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install cloudscraper beautifulsoup4

    - name: Run script
      run: |
        cd $GITHUB_WORKSPACE/hlidac-bytu-clean
        export PYTHONPATH="$PYTHONPATH:$GITHUB_WORKSPACE/hlidac-bytu-clean"
        python3 hlidac.py
